services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/business_case_gz
    depends_on:
      - mongo

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - '4200:4200'
  #   volumes:
  #     - ./:/frontend
  #   environment:
  #     - STYLE=css
  #   depends_on:
  #     - backend

volumes:
  mongo-data:
  mongodb-config:
